{% set version = "1.2.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-st
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/st_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/st/st_{{ version }}.tar.gz
  sha256: d7817c0723bf72e1afbabbba205bb03187c2629c8a552e03f7a918f45c9a4948

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-corpcor >=1.6.8
    - r-fdrtool >=1.2.15
    - r-sda >=1.3.7
  run:
    - r-base
    - r-corpcor >=1.6.8
    - r-fdrtool >=1.2.15
    - r-sda >=1.3.7

test:
  commands:
    - $R -e "library('st')"           # [not win]
    - "\"%R%\" -e \"library('st')\""  # [win]

about:
  home: http://strimmerlab.org/software/st/
  license: GPL-3.0-or-later
  summary: 'Implements the "shrinkage t" statistic  introduced in Opgen-Rhein and Strimmer (2007) and a shrinkage estimate of the "correlation-adjusted t-score" (CAT score) described in Zuber and Strimmer (2009).  It also offers a convenient interface  to a number of other regularized t-statistics commonly  employed in high-dimensional
    case-control studies.    '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
