travis:
  secure:
    BINSTAR_TOKEN: GvsYgS3fklBB3NPNa9falj/Ins760XfF7MHnxuXC1+qWaqa+1Ab2TGBeOmtg8oVtPFjsJWHidLbUFGRoBe4lPKsx9PxDx4AYo2HooVAcALiUzjsTPOauAFdok6UwEpoBAVwA3cncD7te+dYdB1+oHWANHrlcSfPQPSNCJliTkIazMS2iOf4wV0mT0u8qM/uCP8xRV4G6JQAT9o+H6YzgbGaXDG7MUAC53YHAcRzTwlLl+OvkstEFYWdrfP6qTEN45dkfkIFQTzfwMqR381mHIa8Ox4ltIfLnJqwLK5aZ/QI3Z62eusR8wPcWtrzTWVls1WMejCEwz9NvF/kgGMEB+31xPpz3UPXb8LOwO/squxaKiOlsXUuixr9lU45FLrKJkGYefGPAwEqhc+dqp8oIiHM8FEuiU2oz7sMl2VSwVN2cV+KSfEHKSkbY7W+ALOHs8nIFWM7Udl8iKpQ173zbLllyCzSTiDGGMcUpVkRPWx53Wk2ajr++oMJlHesD4+pCkxp94s6qN8lIrDn5ybeOa5u0Q5/nhG4yVE4cjDydmmx2QEy+D4158aCDaPVpjaaLLhXipPL1/tzya61Bi6T4LguE6sWl3PKZc9TtutP3wt59E9PyBLxBE/9lNiJSIACsX0SMnL8F54WN7nU2v6B4erm6KIMw+3QP/M3gr/vLbm0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
