travis:
  secure:
    BINSTAR_TOKEN: CdmpiiG9u1puftycaU+iKVPWo5oKGVxvfIbjPUn5FL5FJz0NPwkTVrmrBuVtp+F0k59ZiJMljMOF30ASjc5i5ajIPqqT1x7QD7hR8SRJa2Ujj4RX0hjVB+1wz7/NE57b343amGtUXvS7RvJntjJKoA1+6tDR6FSMQA6dqyi54YCHwp2LJzeA5zIZnPlOr0fqzVxzLoVvOxddBXTEBG4GP6w7ILvEyjnIOrSxu5cXOuWm4b8JEdGEWAaPRRMqTeU2mruYRMD031zMmSjuKoImWbMruADRU1Spe+OWIJawoVydyYEwj0DEU4tI6tATAXkhoj9lrI0ekYW3zzG+dE1le0XErwUFRNNfwNCqT7ZReqKFt40ASwE9VY5N5dIxjobij4NbOrwEkK2VpS0BqBtQFIeFJ3CFzd2Xuvw0w09SyXA5QrFEK+42n0JJRSHpkQsHZGTgo/11kdWJbIbR32MJsBzhqt3WPurMTVj4AFebNnkl+C8YxtUHC6WxDpBHBUwklF1SVttitQFXcadcFXzJchRzTxxld2REXJsz5Y/yPqBr2erWduwgsUxggkRGgdGoRQBLy56aNKDV9WE+QvgJVxvvUrAqbl59aJmXoD9VFpsdSp3J3qlDAgQF74P5Ek1uW/p7BGOuj6dJw8PUwxANFC818STJrDTn525iwdWwzI0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
