travis:
  secure:
    BINSTAR_TOKEN: f4kDAEEk2/i6PC9RYznEi0UfY8uuUeazSzHp9eVd2m2V3mXK4unSHIGgkGz0zcGRMmjXUfnhIZutgM3jckEm8ipevC3DcwCi5iu7tsmoEDkqwgNI6lx4pzrovbowEP6ilkmbb0LABrjyYrLsKT9TKOxoq5Ppt1gWWU/AVa0Jj4k9VGpa76Tkcq6anY9NDK4HZvpS3CQjG2XUQvVZsNjjoyuGpEm4UeFsVngQ2VF4WbyCJyrBoNdpSkXoJSZw/DcSlMIJoLdVye1vxlQB3Idcmf6RiG0l/c+zpQQ/1il2xwLic3Ckf8iCMqwgH3QukAOu1H6MIVoBNYrG+sawWP9LWN4PQVbtfrU49/MH4sX/oWXK3Fp7Gao883QkwZu92F50fBXT/hEUAL7JP7khgIE161xkOCiMrBsMuhrtey8dxf3T3ZhkK71yBVlTEnesyfomESjKSkYcEwQQ4XHai2JKGHeaY08xu6jHp+sv1FXzw+ly+Mx7AD7rxju1pi8VOeBKMglYqnYyEjuRLd2Q6LXlbnBY8PvA/9fJw8dbYhDgh0xKN5fne/Y1HpojPuinw8Psd+AwmWfMYnH3qU/HNGvcT1S+UtauY58Bf1F0Lf3r8k80vGSuZfMfvTioBFERZdtoduAHSYdn33GHrWq2v/GMt4PPx4vkEww7azy2TIBvdug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
